### PR TITLE
delete app in phonegap-build after build

### PR DESCRIPTION
**Pull request by jrluis**
Hi,

This pull request adds support to delete app in phonegap-build after build.
Add configuration "<deleteAppInPhoneGapBuildAfterBuild>true</deleteAppInPhoneGapBuildAfterBuild>"  to enable the parameter.

This avoid's calling clean when building lots of app's. This way, it avoid leaving phonegap-build app "polluting" the account.

Best regards

### CODE REVIEW

**Comment by chrisprice** [comment]
Thanks @jrluis, sorry it's taken a while to get back on this. Before merging it, I just want to make sure there's not already a way of achieving the same effect. 

E.g. would it work if you [bound the phonegap-build:clean goal to a post package lifecycle phase](http://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag) instead? The only problem I can see with this approach is ensuring that things are cleaned up in the case of failure. As this may or may not be required and something like [--fail-never](http://books.sonatype.com/mvnref-book/reference/running-sect-options.html#running-sect-failure-option) might then be appropriate.

**Comment by jrluis** [comment]
Hi @chrisprice, 
I am using phonegap-build in a jenkins jobs,  its need to fail the jobe when maven fails. This logic will put the red icon and send a failure email :(

If it was not that requirement, phonegap-build:clean could be binded to the end of the lifecycle and use the --fail-never.

**Comment by vasco** [comment]
@chrisprice will @jrluis PR be merged into master and included in a new release?
tks.

**Comment by chrisprice** [comment]
Sorry I've been busy with other stuff, I'll try and get a release out now.

**Comment by chrisprice** [comment]
0.0.10 is now in the [Sonatype staging repo now](https://oss.sonatype.org/content/repositories/releases/com/github/chrisprice/phonegap-build-maven-plugin/) so should sync to maven central soon.

**Comment by vasco** [comment]
@chrisprice Thank you man! :-)

**Pull request merged**
